### ISSUE TITLE
Metallisorvissa vikaa

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/Inventaario#10]
Polttaa sulakkeen ja syötössä ongelmaa.

**Comment by akusav** [comment]
Moottorin hiilet vaihdettu. Nopeuden säätimestä palanut yksi tyristori, 25A vaihdettu tilalle 20A, elektoriin tilattu 25A:nen. Ultranopeita 10A sulakkeita pitää hankkia. Automaatti syöttö poistettu käytöstä manuaalinen syöttö onnistuu.

**Comment by akusav** [comment]
25A tyristori saapunut Arno tietää. Sulakkeita ei ole hankittu vielä.

**Comment by powerpowerpower** [comment]
**препаре**

**Comment by akusav** [comment]
Korajttu!
