### ISSUE TITLE
Lathe tailstock locking mechanism is broken

### ISSUE THREAD

**Issue by Sproketti** [TampereHacklab/Inventaario#100]
The locking mechanism for lathe tailstock is broken and there is a bolt currently in place to keep the machine usable.

The bolt in the mechanism is hold in place by pin that breaks easily if too much force is applied. I fixed this a couple of months ago, but did not have time to take care of it right now.

Is there a need to make stronger mechanism or is this weak pin in place by design to protect other parts of the lathe?

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/d5d0c17c-76fd-4fc2-ab49-11948e88ed03)

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/6e8602ab-6634-47e9-999b-ab7fbcac88ef)

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/6156ed9c-83e3-4035-82cb-3436472f4111)

**Comment by tswfi** [comment]
I'm guessing it is to protect other parts (or the threads).

Not sure if these would work https://www.puuilo.fi/hercules-putkisokka-nippelisarja (I will bring a set anyway)

**Comment by Sproketti** [comment]
I was thinking the same. I have those pins in my smartstore box if someone wants to tackle the issue before I have time.

**Comment by tswfi** [comment]
Hain sokat otto asensi, toimii taas

![PXL_20240128_160434642.jpg](https://github.com/TampereHacklab/Inventaario/assets/1352132/455b34c4-17d1-4da8-a9b6-a41449b63636)
