### ISSUE TITLE
Plasmaleikkurin Y-akseli ei toimi

### ISSUE THREAD

**Issue by pinq-** [TampereHacklab/Inventaario#107]
Plasman y-leikkuri ei liiku. Virta tulee moottorille. Todennäköisesti moottorinohjaus mennyt. Vaatii etsimistä.

**Comment by Ottopoeka** [comment]
Y vaihdettu ohjainkortin portista 2 porttiin 3 kortin valmistajan numerointia käyttäen. (Tussilla korttiin merkatut numerot väärin). Jälleen toimii.
