### ISSUE TITLE
Maalaamo varattu CNC-jyrsimen osien maalaukseen

### ISSUE THREAD

**Issue by kengu2** [TampereHacklab/Inventaario#108]
Metallijyrsin etenee, suojapeltejä maalataan pohja- ja pintamaalilla. Maali on ikävä kemikaali ja maalauksen jälkeen tilaan ei voi mennä ilman ihan oikeita hengityssuojaimia.

Arvioutu kesto, maaliskuun 14. päivä asti.

**Comment by pinq-** [comment]
Maalaminen done! <3
