### ISSUE TITLE
Sorvin moottori käryää. Sorvi poissa käytöstä.

### ISSUE THREAD

**Issue by Sproketti** [TampereHacklab/Inventaario#110]
Sorvi alkoi kesken kaiken haista pahalle ja savuta. Pikaisen tutkinnan jälkeen vika paikannettu moottoriin, josta savu ja käry lähtee.

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/7021c7e7-aa78-420d-b01f-3872dc15ca16)

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/ca0c25d3-d19a-40cc-bbd2-8302b796b575)

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/1a6b071d-0404-4303-9d8f-aadceac379a3)

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/77a201a9-c635-4013-a7ca-f962d7d54800)

**Comment by Sproketti** [comment]
Moottori purettu irti ja todettu vaativan uudet hiilet. Ei varmuutta onko tilattu, mutta aiheesta keskusteltu asiakanavalla 10.3.2024.

Puretut osat ja irroitetut johdot merkattu. Koneen päälle laitettu lappu, joka kertoo koneen olevan käyttökiellossa.

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/b3bbd5f2-d033-439a-8ac4-54fdcdfb8c51)

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/e05303b5-2951-48cc-b565-9ca9319004b0)

![image](https://github.com/TampereHacklab/Inventaario/assets/18136801/5e742a29-3078-4693-94ec-07ea53798bc1)

**Comment by tswfi** [comment]
Uusi moottori laitettu tilaukseen.

**Comment by tswfi** [comment]
Uusi moottori saapunut

**Comment by tswfi** [comment]
Uusi moottori asennettu ja kytkennät kunnossa.

Vain hitaampi alue käytössä (kiilahihnapyörä ei mahdu tarpeeksi syvälle). Tehdään tuosta uusi issue koska ei estä käyttöä.
