### ISSUE TITLE
Maalaamon viimeistely ja käyttöönotto "vanha kemiahuone"

### ISSUE THREAD

**Issue by akusav** [TampereHacklab/Inventaario#13]
- [ ] seinien pintakäsittely
- [x] rakojen tiivistys
- [x] kärypoistot

**Comment by pinq-** [comment]
- [ ] Pölyn/käryn poiston tekeminen. 
   - [ ] Suunnitelman tekeminen ilmanpoistolle
   - [ ] Vaatii jonkun "uskalluksen" aloittaa tekemään. 
   - [ ] Vetokaapit vaativat oman ilmanvaihdoin myös. (Käytännössä imu ilma imettäisiin niiden kautta huoneesta)
   - [ ] Materiaalin hankkiminen
- [ ] Uudelleen järjestely
- [x] Raot tiivistetty
- [x] Ulkopinnat käsitelty

**Comment by akusav** [comment]
Maalaamo tarvii minimissään:
- keittiölle menevien vesiputkien kiinnityksen seinään (roikkuvat nyt hasardisti miten sattuu)
- suodattimen poistokanavaan, alkuun varmaan riittää puupuolellakin käytössä oleva suodatinkangas (ettei maalisumu/pöly mene masiinaan)
- suojamaadoitettu jatkojohto poistopuhaltimelle
- tilan raivaus

**Comment by akusav** [comment]
- Poistopuhaltimen käyttökytkimen asentaminen

**Comment by pinq-** [comment]
Tämä lienee "viimestelty". Seuraavat askeleet voidaan lisätä seuraaviksi issukoiksi
