### ISSUE TITLE
Silikonisuojus huonosti kiinni

### ISSUE THREAD

**Issue by akusav** [TampereHacklab/Inventaario#14]
"3d-printterissä taitaa olla z-akselissa ja/tai kalibroinnissa häikkää. mikään ei tarttunut ja 'preamblestakin' tuli morsekoodia. tulostuslevy on jo osittain 'kaiverrettu'."

**Comment by Miggov** [comment]
Kesällä toimi, mikähän tilanne mahtaa olla nyt? Printti ei vaikuttanut tarttuvan taas hiljattain testaillessa ja lämmitinelementin silikonisuojus näyttäisi roikkuvan, voisiko tuo repiä printit irti?

**Comment by Miggov** [comment]
En saa otettua taskia itelleni mutta otan tän nyt hoitoon ja tilaan uusia silikonisukkia. Nuo voisi yrittää köyttää jollain mielellään ruostumattomalla jekkulangalla kiinni etteivät pääse putoamaan ja tuhoamaan printtiä tai pahimmillaan blokkaamaan suutinta

**Comment by pinq-** [comment]
Tämä on korjattu ja pävitetty. Tämän voi sulkea
