### ISSUE TITLE
Nextcloud palvelun lisääminen

### ISSUE THREAD

**Issue by pinq-** [TampereHacklab/Inventaario#16]
Asennettu, mutta ei käytössä. 

- [ ] keycloack toiminnan varmistaminen?

**Comment by tswfi** [comment]
* [x] nextcloud päivitelty uusimpaan stable versioon
* [x] konfiguraatio ongelmat korjailtu (dav, well-known, hsts jne traefik:llä)
* [x] keycloak authentikaatio laitettu käyttöön
* [x] upcloud backup todettu toimivaksi

Tämä siis valmis, suljen pois
