### ISSUE TITLE
Loungeen työpöydän tekeminen

### ISSUE THREAD

**Issue by pinq-** [TampereHacklab/Inventaario#17]
Loungen työpöytä pieniprojekteille tai läppärillä työskentelyyn (Mallia voisi ottaa edellisestä "baari"pöydästä)
- [ ] Loungeen työpöydän tekeminen
- [ ] integroidut sähköpistorasiat
- [ ] RJ45 pistorasiat

**Comment by vranki** [comment]
Tämä issue pitäisi määritellä tarkemmin tai pilkkoa osiin. Pitäisi olla selkeä yksittäinen tehtävä josta voidaan selvästi tietää koska se on valmis. Ehdottaisin että ensimmäinen tehtävä on palaveri labilla jossa keksitään konkreettisia tehtäviä.

**Comment by Cromfel** [comment]
Pilkottu alitehtäviin tiketin siällä, jos kokonaisuudet suurempia, voi eritellä ticketeihin

**Comment by kengu2** [comment]
Loungea on taidettu pyöräyttää uuteen uskoon noin kahdesti viime joulukuun jälkeen. Tästä pitäisi varmaankin olla jotain tarkempaa suunnitelmaa, pohjapiirrosta tai jotain.

**Comment by tswfi** [comment]
Tässä muodossa tämä taski ei etene.
Suljen pois.
