### ISSUE TITLE
Laserleikkurin "tehoputken" vaihtaimen

### ISSUE THREAD

**Issue by pinq-** [TampereHacklab/Inventaario#18]
Edellisessä laser alkoi hajoamaan ja aiheutti huonoa leikkuuta. Ei ollut enää korjattavissa, koska säde hajosi jo putken sisällä, joten uusi oli tilattava. 

- [x] Uusi putki tilattu
- [x] Saapunut labille
- [x] Asennettu

**Comment by tswfi** [comment]
Arno ja kumppanit olivat tehneet tämän jo ennen joulua.
Isot kiitokset!
