### ISSUE TITLE
Puusorvin kelkka ei liiku kunnolla.

### ISSUE THREAD

**Issue by pinq-** [TampereHacklab/Inventaario#19]
Toisen (omatekoinen, sininen) puusorvin kelkka ei liiku kunnolla toiseen suuntaan. On yritetty puhdistaa kelkan reikiä, mutta ei auta. Jotain pitäisi keksiä.

**Comment by pinq-** [comment]
Yritetty hioa ja isontaa reikää: ei auta. Kiilautuu edelleen kiinni toiseen suuntaan. Ehkä parempi muuttaa kiinnitystapa samanaliseksi kun päätykelkassa ( kahtia ja kiristys keskeltä?) Tai sitten pyöristää kunnolla reijät kun uusi metalli cnc valmistuu.

**Comment by tswfi** [comment]
![image](https://user-images.githubusercontent.com/1352132/190574062-409a70bf-f564-45d5-96e6-91ae53724487.png)
