### ISSUE TITLE
NFC-ovenavaus

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/Inventaario#2]
Asennettu. Käyttökunnossa. Paranna näytön sääolosuhteiden kestoa.

**Comment by vranki** [comment]
Vaatii ilmeisesti koteloinnin ja paikalleen asennuksen.

**Comment by pinq-** [comment]
- [x] Asennettu ja koteloitu
- [ ] Koodin päivittäminen niin, että sisä ovi pysyy kauuempaa auki.
- [ ] Näytön tarpeen pohtiminen? Jos tykkää glitch taiteessa, nii se näyttää hienolta kosteella säällä, mutta pidemmän päälle saattaa hajoittaa laitteen.
- [ ] Enemmän kuin yhden avaimen rekistörinti?

**Comment by vranki** [comment]
NFC-avaus ei toimi tällä hetkellä, lukija ei reagoi mitenkään. Ei tietoa tarkemmasta syystä.

**Comment by vranki** [comment]
Toimi taas eilen. Ei tietoa onko joku korjannut vai mistä johtuu.

**Comment by vranki** [comment]
@pinq- teetkö omat issuet noista rukseista. Avaus toimii, nuo ovat jatkokehitysideoita. Suljen tämän tiketin.

Ps. Enemmän kuin yhden avaimen rekisteröinti tekisi helpoksi avainten tekemisen kavereille ja sitä ei mun mielestä haluta.
