### ISSUE TITLE
Labin puhelinnumero ovelle | Lab phone number on door

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/Inventaario#21]
Laitetaan labin puhelinnumero ovelle. Plussapisteitä hakkerihenkisestiä toteutuksesta.

**Comment by pinq-** [comment]
Puhelinnumero on +358 93157 6905

**Comment by tswfi** [comment]
![PXL_20230914_155740220.jpg](https://github.com/TampereHacklab/Inventaario/assets/1352132/41361424-dbf8-4b2c-a8a7-1073eea9eb34)

Siellä näyttää olevan
