### ISSUE TITLE
Puhtaanmaalaamon käyttöönotto

### ISSUE THREAD

**Issue by akusav** [TampereHacklab/Inventaario#22]
- [x] vetokaappien kärypoistojen kurttuputken asennus

**Comment by tswfi** [comment]
Vetokaappien poistot on valmiit (kuristimineen)
Elegoo mars koeajettu. Siivousta olisi vielä tehtävänä

**Comment by kengu2** [comment]
Onko tässä vielä jotain oleellista kesken?
