### ISSUE TITLE
Ilmanvaihto, perhosventtiilien asentaminen maalaamon kärynpoistokanavaan

### ISSUE THREAD

**Issue by nuulis** [TampereHacklab/Inventaario#29]
Perhosventtiilien asentaminen maalaamon käryimurin kanavaan. Toinen kanavapuhaltimen jälkeen (ulkosuuntaan) ja toinen viilennyskonetta varten keittiön jääkaapin kohdalle. Molemmat niin, että ne aukeavat ulosmenevää ilmaa varten.

**Comment by tswfi** [comment]
![Uploading 16535830421769212472021788149160.jpg…]()

**Comment by tswfi** [comment]
![1653586783436867002503225367895](https://user-images.githubusercontent.com/1352132/170544615-e3fcf938-acaa-4a53-bcd0-8d5a26e0ece9.jpg)
Done. 

Ja jäähykin on jo jääkaapin päällä
