### ISSUE TITLE
Ilmanvaihto, kanava maalaamon ja puhdasmaalaamon väliin

### ISSUE THREAD

**Issue by nuulis** [TampereHacklab/Inventaario#30]
Uusi reikä seinään ko. tilojen väliin. Samaan kohtaan kuin nykyinen ylhäällä oleva, mutta alas n. 20 cm lattiasta. Tekee maalaamosta alipaineisen tilan keittiöön nähden, myös silloin, kun poistopuhallin on sammuksissa, jolloin käryt kulkeutuvat puhdasmaalaamon kautta poistokanavaan.

**Comment by Miggov** [comment]
![20240303_194037](https://github.com/TampereHacklab/Inventaario/assets/15943970/8c8d8626-87ec-40ab-a91f-0acdd3ccfc8d)
Tuolla on nyt perhosventtiili. Käryimuri päällä käy selvä veto. Eikai tähän muuta tarvita?
