### ISSUE TITLE
Ilmanvaihto, laahuksen lisäys maalaamon oveen

### ISSUE THREAD

**Issue by nuulis** [TampereHacklab/Inventaario#33]
Estää käryn kulkeutumista maalaamosta keittiön käytävään

**Comment by tswfi** [comment]
![16535812017373429229534817318848](https://user-images.githubusercontent.com/1352132/170528099-f4b8dc73-6979-4721-ba6c-7510c66b0fe5.jpg)
Almost perfect (missing one screw as we ran out)
