### ISSUE TITLE
Uuden mittalaitepöydän asennus

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/Inventaario#35]
Mittalaitepöytä on nyt labilla:

![](https://matrix.hacklab.fi/_matrix/media/r0/download/hacklab.fi/RqdJTZWcygenosWlqaAzlRTu)

Tälle pitäisi päättä asennuspaikka ja suorittaa asennus. Pöytä painaa aika paljon joten tarvinee jonkinlaiset
custom jalat. Pöytään voi integroida oskilloskooppeja sun muita laitteita. Tyhjiä etupaneeleita tuli mukana N
kpl.

Ennenkuin työ on valmis, pöytään tulee tehdä kilpi (tarratulostetimella jos laiskottaa) jossa lukee: "Lahjoittanut Tekn. Tri Tiiti Kellomäki 8.6.2022".

Kuvia mukana tulleista varusteista:

![](https://matrix.hacklab.fi/_matrix/media/r0/download/hacklab.fi/EPQyyYibOnDLgZuBcQxHezLo)

![](https://matrix.hacklab.fi/_matrix/media/r0/download/hacklab.fi/DXGiXeCURmwGrYCqokSVEqTJ)

**Comment by akusav** [comment]
Johonkin tää katos mutta mihin? Voidaan varmaan sulkea tää issue?

**Comment by pinq-** [comment]
Joo. Ei ole näkynyt.
