### ISSUE TITLE
Pieni vihreä nauhahiomakone, rullan laakerit

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/Inventaario#4]
Kanavalta tulleesta raportista:

puupuolen vihreästä pienestä nauhahiomakoneesta leipo ilmeisesti ei-vetävän rullan laakerit. Alustavasti otin siitä hiomanauhan pois, että siitä voi vielä käyttää hiomakiekko osaa.

**Comment by tswfi** [comment]
Teemu kommentoi kanavalla

Tsekkasin tuon pienen hiomakoneen ja normaalisti toimii. Laitoin vähä wd40 ja pyörittelin. Kaipais ehkä perusteellisempaa putsausta vielä ja kunnon vaseliineja laakereihin. Että jos jollakulla on aikaa niin oispa kiva jos putsais!

**Comment by akusav** [comment]
- [ ] selvitä onko meillä vielä tämmönen kone
- [ ] jos on niin tee wiki sivu ja lisää sinne kuva koneesta tai vaihtoehtoisesti sulje issue

**Comment by Sandplum** [comment]
the machine is in the storage area, currently

**Comment by tswfi** [comment]
![PXL_20240206_203454733.jpg](https://github.com/TampereHacklab/Inventaario/assets/1352132/d2fe25a3-8740-4a68-94d3-5af1a9009233)
