### ISSUE TITLE
Lämpöongelma 3D-tulostimessa

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/Inventaario#40]
Asiakanavalta:

Laitoin printterin päälle jo lapun mutta ilmotan täälläkin että 3d tulostimessa on vikaa lämpötilan kanssa
Mahdollinen syypää voi olla rispaantunut johto mutta itsellä ei ollut aikaa katsoa tarkemmin

**Comment by tswfi** [comment]
Asiakanavalta jatkoa:
```
Lukas Friman
Sörkin vähän johtoja ja tarkistin että on kunnolla kiinni ja nyt lähti tulostamaan taas normaalisti
Tarkkailen kuitenkin tilannetta
```

Suljen pois. Avataan takaisin jos on tarvetta.
