### ISSUE TITLE
Hihnatulostin ei pelaa. Creality CR-30 3DPrintMill

### ISSUE THREAD

**Issue by pinq-** [TampereHacklab/Inventaario#44]
Tulostus ei jää petiin kiinni. Voi vaatia paljon säätöä.
Malli: Creality CR-30 3DPrintMill

**Comment by pinq-** [comment]
Tulostin tarvitsee uuden virtalähteen. 
Todennäköisesti tämä malli: https://www.3dprima.com/spare-parts-accessories/manufacturers/creality-3d/creality-3d-cr-30-power-supply_27009_8454

**Comment by tswfi** [comment]
suomalainen source https://www.an-cadsolutions.fi/tuote/creality-3d-cr-30-virtalahde/ (kiitos Arno löytämisestä)

Jos olisi tiedossa koko ja voltit ja ampeerit niin voisi myös katsoa tipahtaako tuollainen jostain syliin.

Tosin mietin myös että kannattaako tuohon tuota 40€ investoida jos on muutenkin tarttumisongelmaa pedissä? Jos laittaisi vaan myyntiin ilman poweria?

**Comment by pinq-** [comment]
Virtalähde laitettu tilaukseen

**Comment by pinq-** [comment]
Virtalähde asennettuna ja toimii. Vaatii säädön kohdilleen
