### ISSUE TITLE
Laserleikkurin kohdistuslaser

### ISSUE THREAD

**Issue by brndd** [TampereHacklab/Inventaario#45]
Kohdistuslaserin johdot ovat kärsineet. Vaakasuorassa oleva kohdistin ei pala ollenkaan (johdot kokonaan poikki) ja pystysuorassa olevassa on rajua kosketushäiriötä.

Ei vaikuta varsinaisen laserleikkurin toiminnallisuuteen, mutta vaikeuttaa laserin kohdistamista työstöpalaa asetellessa.

**Comment by tswfi** [comment]
Kohdistuslaserit fiksattu, kiitos.
