### ISSUE TITLE
Ison vannesahan vetohihnan akselissa klappia

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/Inventaario#5]
Vetohihnan akselissa klappia, huolto käynnissä

![Screenshot_20210130-111254](https://user-images.githubusercontent.com/1352132/106352489-4424d300-62ec-11eb-8264-cf6c4ee3cb67.png)

**Comment by sbeach92** [comment]
Akselissa ja hihnapyörässä oli klappia. Hankin uuden hihnapyörän taperlock kartiolla. Akselia sorvattaessa selvisi että sitä on aikanaan korjattu. Korjausta on ilmeisesti hätiköity ja laskerilinjat eivät olleet muun akselin suuntaisia. Hihnapyörän lieriö ja terän vetopyörän kartio korjauskoneistettiin. Kone on nyt käyttökunnossa
