### ISSUE TITLE
Tarraleikkurille ohjeet wikiin  |  Add Instructions for the sticker cutter to the wiki

### ISSUE THREAD

**Issue by akusav** [TampereHacklab/Inventaario#50]
- [x] tee joukkorahoitetulle tarraleikkurille wiki sivut
- [x] kirjoita käyttöohjeet
- [x] tee tarraleikkurille pölysuoja  |  make a dust cover for the sticker cutter

**Comment by Sandplum** [comment]
![summa_dust_cover](https://github.com/TampereHacklab/Inventaario/assets/143935229/1e4354ae-66bc-42fc-9295-2a86c62d55af)
