### ISSUE TITLE
Maalaamon poistopuhallin resonoi loungessa.

### ISSUE THREAD

**Issue by 314Sami** [TampereHacklab/Inventaario#62]
Todo: jos mitenkään mahdollista, puhallin olisi hyvä olla ulkona.

Väliaikaisratkaisuna kiinnittäminen tukevammin tai tärinänvaimentimien käyttö.

**Comment by tswfi** [comment]
@314Sami onko tämä vielä ongelma? En ainakaan ole viimeaikoina huomannut mitään ongelmaa?
