### ISSUE TITLE
Puruimuri/Höylän puruimuri  |  Dust Collector for the Planer

### ISSUE THREAD

**Issue by nuulis** [TampereHacklab/Inventaario#67]
- [ ] Uusi kytkinrasia (on-nappi takkuaa, voisi vaihtaa koko boksin)
- [x] Purusäiliön kansi tiiviimmäksi
- [x] Rakenna/hanki sykloni
- [ ] Hanki parempi suodatin ja rakenna sille adapteri
- [x] Hanki voimavirta-adapteri, jotta imurin saa sähkönsä samasta rasiasta höylän kanssa
- [ ] Rakenna automaattikäynnistys
- [x] Pidempi sähköjohto

**Comment by nuulis** [comment]
- [ ] Uusi kytkinrasia (on-nappi takkuaa, voisi vaihtaa koko boksin)
- [ ] Parempi panta purusäkille
- [ ] Pidempi sähköjohto

**Comment by Sandplum** [comment]
![planer_dust_collector](https://github.com/TampereHacklab/Inventaario/assets/143935229/f58edc04-fa43-4316-9dba-66b968813bd4)
