### ISSUE TITLE
Metallivannesaha terä poikki  |  Metal bandsaw blade broken

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/Inventaario#69]
Ja varaterä poikki myös.   |  And a spare blade broken too.

- [ ] 2x terä tilaukseen  |  order 2x blades
- [ ] asennuksen yhteydessä tarkistus onko jotain vikaa että syö teriä  |  during installation check if there is something wrong with the blades

**Comment by pinq-** [comment]
Joppe tilas uuden ja korjasi laitteen. Kiitos Joppe<3
