### ISSUE TITLE
Puusorvi ei pyöri

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/Inventaario#73]
- [ ] kanavalla raportoitu että ei pyöri

**Comment by pinq-** [comment]
Taajusmuuntaja sekoilee. Mitään ei tapahdu, kun yrittää tehdä sillä jotain. Vaatii jonkun joka tietää taajusmuuntajista

**Comment by tswfi** [comment]
Tamun potikkaa väännelty irtonaisena. Potikan johto kolvattu ja testattu, toimii.
