### ISSUE TITLE
Puruimuri/kermanvärinen Scheppach

### ISSUE THREAD

**Issue by nuulis** [TampereHacklab/Inventaario#74]
- [x] Rakenna/hanki ja asenna sulkupellit koneille
- [ ] Rakenna/hanki sykloni järjestelmään
- [ ] Päivitä imurin moottori tehokkaammaksi
- [ ] Jatka putkistoa sorv(e)ille

**Comment by nuulis** [comment]
Imuri siirretty vannesahan toiselle puolelle cnc:n imurin tieltä. Availlaan uusia issueita kun tulee konkreettisia parannusehdotuksia.

**Comment by MikkoMyntti** [comment]
Vilkaisin puruimurin keskusta. Vaikuttaa olevan valmiita ohjauksia, mutta piirikaaviot puuttuu.
Onko piirikaavioita mahdollista kysyä ostopaikasta? Tämä säästäisi melkoisesti vaivaa, jos kuvat löytyy.

Tehonsyöttöön varaudutaan puupuolen uudessa keskuksessa.
Rakennan keskukseen myös varauksen:
Jos purusäiliö on täynnä -> merkkivalo keskuksella ja pistorasioista katkeaa sähkö.

![Image](https://github.com/user-attachments/assets/9e47f56b-81af-48fc-8864-fee43b3244e2)

![Image](https://github.com/user-attachments/assets/4513cbd5-83d2-4d11-8435-11db02745cba)
