### ISSUE TITLE
Jättiläistulostimen käyttöönotto

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/Inventaario#8]
Do the needful. Mitä tarvitaan että saadaan käyttöön?

**Comment by akusav** [comment]
Korjaa multisensor error. Soita canonin huoltoon tai hanki uusi multisensor. Takeita korjautumisesta ei ole.

**Comment by akusav** [comment]
Tulostin purettu ja lajiteltu. Odottaa kuljetusta kierrätykseen.
