### ISSUE TITLE
Laserin tamu NXOPTA2 virhe

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/Inventaario#80]
Käynnistyksen jälkeen vilkuttaa fault.
Reset napin painaminen korjaa tilanteen

**Comment by tswfi** [comment]
![PXL_20231107_190633397](https://github.com/TampereHacklab/Inventaario/assets/1352132/c16054d9-b30f-4434-a2d2-bf28c88b1b8c)

**Comment by turski** [comment]
Tarpeeton lisäkortti poistettu tamusta ja ongelma poistui.
