### ISSUE TITLE
Ilmanvaihto Spraymaalaushuone | Spray Paint Room Ventilation

### ISSUE THREAD

**Issue by Ceravyn** [TampereHacklab/Inventaario#88]
Minimissään siirrä spraymaalaushuoneen sisällä oleva imuriseinä sekä maalauspöytä huoneen oik. takanurkkaan (vinottain) tai vielä parempi: rakenna oik. takanurkkaan uusi  laajempipintainen kaareva imuriseinä (esim. laseroidusta akryylistä tai reikälevystä) jotta käryt menevät tehokkaammin poistopuhaltimeen.

Vaatii:
- [x] Kaarevan reikälevyn ja sille kehikon joka sopii nurkkaan. Vaihtoehtoisesti esim. kolme suoraa reikälevypaneelia kaarevaan muotoon asennettuna.
- [x] Kulmapöydän tms
- [x] IV-hormin lyhentämisen (tulee nyt keskelle huonetta, riittäisi jos tulee vain nurkkaan) 

IV-hormijärjestelmän tarkistus ja parantelut:

- [x] Tarkista, ettei hormista ole vuotoa keittiön / loungen puolelle. Tarvittaessa tuki vuotokohdat.
- [x] Asenna tehokkaampi poistoilmapuhallin. Läbillä lojuu useampia, ota yksi käyttöön.

Ovi:
- [x] Hanki ja asenna ovenkarmiin tiivistenauha

Vas. sivuseinä:
- [x] Tuki ei-spray-maalaamon ja spraymaalaamon välisestä seinästä siihen poratut isoimmat läpivientiaukot jotta käryt eivät leviäisi puolelta toiselle.

**Comment by nuulis** [comment]
Aina löytyy paranneltavaa, mutta avataan niille uusia issueita kun keksitään konkretiaa.
