### ISSUE TITLE
Repair blue canister vacuum cleaner

### ISSUE THREAD

**Issue by Sandplum** [TampereHacklab/Inventaario#96]
Blue canister vacuum cleaner is not functioning (reported by Arno and Teemu).

Once repaired, return the vacuum cleaner to the laser cutter corridor.

**Comment by tswfi** [comment]
Nilfisk Alto

Cable was broken near the socket. Fixed.
Power switch was acting up. Feels fixed now.
Motor overheats. Not possible to open. Replacement part https://www.huoltopalvelu.com/Poelynimurin-moottori-Domel-4673402-5

**Comment by tswfi** [comment]
And it seems that the suction power control is at full blast all the time, no one wants to run this at half speed so no need to debug it deeper...

**Comment by tswfi** [comment]
tsw orders new motor in a moment

**Comment by tswfi** [comment]
Motor ordered, wont probably get here before christmas though...

**Comment by tswfi** [comment]
Working again

![PXL_20231223_130422608.jpg](https://github.com/TampereHacklab/Inventaario/assets/1352132/a78d64ce-3ddb-42c1-909e-e9b21a55fdc5)
