### ISSUE TITLE
Ei toimi. Taajuusmuuttajan virhe Fu03

### ISSUE THREAD

**Issue by Ottopoeka** [TampereHacklab/Inventaario#99]
Taajusmuuttaja antaa virhettä Fu03 eikä anna liikuttaa akseleita.  Kenties huonoa sähköä? Karli ja Arno ovat jokseenkin tietoisia ongelmasta.

**Comment by spiikki** [comment]
Toimii satunnaisesti. Taajuusmuuntaja virtakipuilee.

**Comment by tswfi** [comment]
Mikä tamu siinä on?
Olisiko kuvaa?

**Comment by Ottopoeka** [comment]
![IMG_20240125_193705_MP.jpg](https://github.com/TampereHacklab/Inventaario/assets/36885898/ac7bb786-3f34-4d0e-af24-d1c607413131)

**Comment by sbeach92** [comment]
![Screenshot_20240206-201316~2](https://github.com/TampereHacklab/Inventaario/assets/75908489/c1c40390-a501-4a10-9553-32a6d9484e21)

Ylivirtaa, voi johtua esim alijännitteestä. Enable päällä ennenku tamussa virrat? Huono jänniteen syöttö.

https://wiki.tampere.hacklab.fi/_media/tyokaluja/labcncvfd.pdf

**Comment by pinq-** [comment]
Oisko mahkuja kokeilla toista tamua? Minkälaisen se vaatisi?

**Comment by Ottopoeka** [comment]
![IMG_20240215_130522_MP.jpg](https://github.com/TampereHacklab/Inventaario/assets/36885898/0b6eb1bb-4ee0-493c-b722-50d47163e13d)

**Comment by Ottopoeka** [comment]
Vaihejännite oli mitattuna about 390. Muutin parametrin "FC.0 Under voltage protection level 360～460V" arvosta 380 370:een ja virhe katosi
